export const MIN_ROWS = 10;
export const MAX_ROWS = 100;
export const DEF_ROWS = 50;
export const MIN_COLS = 10;
export const MAX_COLS = 100;
export const DEF_COLS = 50;
export const MIN_FILL = 10;
export const MAX_FILL = 90;
export const DEF_FILL = 25;
export const DEF_VELOCITY = 100;
export const DEF_AUTOMATON = 15;
export const EMPTY_CELL_COLOR = "#ececec";
export const DEF_MIN_COLOR = "#FFFF00"; //yellow
export const DEF_MAX_COLOR = "#006400"; //darkgreen
